project_id = "lgjogrvydtwxxsjarrxm"

[functions.bitrix-sync]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = true

[functions.quote-sync]
verify_jwt = true

[functions.product-webhook]
verify_jwt = false
